name: Automerge PRs from PipedreamBot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: github.actor == 'astro215' && github.event.pull_request.head.ref == 'Br2' && github.event.pull_request.base.ref == 'Br1'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge PR
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout -qf FETCH_HEAD
          git merge --no-ff -m "Auto-merged by GitHub Actions" ${{ github.event.pull_request.head.sha }}
      - name: Push changes
        run: git push origin ${{ github.event.pull_request.base.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
