name: Automerge PRs from PipedreamBot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: github.actor == 'astro215' && github.event.pull_request.head.ref == 'br2' && github.event.pull_request.base.ref == 'br1'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch PR and merge
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git checkout pr-branch
          git pull origin Br1  # Pull the latest changes from Br1 (base branch)
          git merge --no-ff -m "Auto-merged by GitHub Actions" pr-branch

      - name: Push changes
        run: git push origin Br1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
