name: Auto Merge Pull Request

# Trigger the workflow on pull request creation, reopening, or when new commits are pushed to the pull request.
on:
  pull_request:
    branches:
      - br1  # The target branch for the PR (base branch)

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR is from br2
        id: check-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // Check if the PR is from br2
            if (context.payload.pull_request.head.ref === 'br2') {
              core.setOutput('is_valid_pr', 'true');
            } else {
              core.setOutput('is_valid_pr', 'false');
            }

      - name: Auto merge PR
        if: steps.check-pr.outputs.is_valid_pr == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
